#! /bin/sh

here=$( dirname $0)
confdir=$here/config/
setdir=$here/settings/
kustomize=$here/kustomization.yaml

kustomizeadd=$here/kustomizeadd.yaml
starttag="# MARK - Generated by mkconfig.sh"
endtag="# ENDMARK - Generated by mkconfig.sh"

rm -f $kustomizeadd
echo $starttag > $kustomizeadd
echo "- name: canasta-config" >> $kustomizeadd
echo "  files:" >> $kustomizeadd
ls -1 $confdir | awk '{ print "  - " $1 "=config/" $1 }' >> $kustomizeadd
echo "- name: canasta-settings" >> $kustomizeadd
echo "  files:" >> $kustomizeadd
ls -1 $setdir | awk '{ print "  - " $1 "=settings/" $1 }' >> $kustomizeadd
echo $endtag >> $kustomizeadd

sed "/$starttag/,/$endtag/d" $kustomize | sed "/^configMapGenerator:/r $kustomizeadd" > $kustomize.new
rm $kustomizeadd
mv $kustomize.new $kustomize
