apiVersion: k8s.mariadb.com/v1alpha1
kind: Database
metadata:
  name: db
spec:
  name: mediawiki
  mariaDbRef:
    name: db-instance
  characterSet: utf8
  cleanupPolicy: Delete
  requeueInterval: 10h
  retryInterval: 30s